### ISSUE TITLE
Great project

### ISSUE THREAD

**Issue by pidgeon777** [polirritmico/telescope-lazy-plugins.nvim#1]
First, congratulations on your project.

I would suggest you to also post your plugin here:

https://www.reddit.com/r/neovim/
https://github.com/rockerBOO/awesome-neovim

**Comment by polirritmico** [comment]
Hi. Thanks for your kind words!
I've already posted it in those two places:

- https://www.reddit.com/r/neovim/comments/1awll29/introducing_new_telescope_picker_extension/
- Under the Search section: https://github.com/rockerBOO/awesome-neovim?tab=readme-ov-file#search

I hope you find the plugin useful, and please feel free to report any issues or share ideas for improvement.

**Comment by ivuorinen** [comment]
I just randomly found this project and didn't know one can be this exited about a neovim telescope plugin 😄 

Thank you for your great work!

(Didn't want to open a new issue for this, I hope you both don't mind getting notified 😅)

**Comment by polirritmico** [comment]
> I just randomly found this project and didn't know one can be this exited about a neovim telescope plugin 😄
> 
> Thank you for your great work!
> 
> (Didn't want to open a new issue for this, I hope you both don't mind getting notified 😅)

No problem at all. Thanks!!
