### ISSUE TITLE
[Feature] Dependency visualization for plugins

### ISSUE THREAD

**Issue by pidgeon777** [polirritmico/telescope-lazy-plugins.nvim#15]
Firstly, I would like to commend you on developing this plugin - it's truly beneficial!

I would like to propose an additional feature that I believe would be equally useful: the ability to return a table illustrating the dependency relationships between the installed plugins.

Here's an example:

```lua
{
  {
    name = "plugin1",
    requires = {"plugin2", "plugin3"},
    required_by = {"plugin4", "plugin5"}
  },
  {
    name = "plugin2",
    requires = {"plugin3"},
    required_by = {"plugin1"}
  },
  {
    name = "plugin3",
    requires = {},
    required_by = {"plugin1", "plugin2"}
  },
  {
    name = "plugin4",
    requires = {"plugin1"},
    required_by = {}
  },
  {
    name = "plugin5",
    requires = {"plugin1"},
    required_by = {}
  }
}
```

This information could then be displayed by your plugin in a table, or provided to the user via an API. This would allow them to use it to generate a graphical visualization of the dependencies, for instance, using tools like `Graphviz`. What are your thoughts on this?

**Comment by polirritmico** [comment]
Thank you for your suggestion and for taking the time to share your idea. I’ve given it some thought, but I believe this functionality is non-trivial to implement and too out of scope for a telescope picker.

Regards

Edit:
PRs are welcome if you can implement it as a custom action or in a way that introduces low friction to the existing code. Something like an action to print a list of plugins that depend on the selected one, etc.
