### ISSUE TITLE
Feature Request: Grep Plugin

### ISSUE THREAD

**Issue by kevintraver** [polirritmico/telescope-lazy-plugins.nvim#6]
Feature Request: Ability to grep plugin using telescope:

Could be similar to how https://github.com/tsakirist/telescope-lazy.nvim has `live_grep`.

Happy to help with a PR.

Thanks for the awesome plugin!

**Comment by polirritmico** [comment]
Added in b254afb

Thanks again for taking the time to propose this feature and use the plugin.
Please feel free to open a new Issue if something is wrong or anything.

Regards

**Comment by kevintraver** [comment]
Just tried it out, and it works great!

It would be also be helpful to have the other features in **telescope-lazy**:

- open_in_file_browser
- open_in_find_files
- open_in_terminal
- open_plugins_picker (this is handy for 'going back' in telescope after entering a second search.

I'll open up a new issue, and once again I am happy to help with a PR.
